"""initial production schema

Revision ID: 9aeb8666b39c
Revises:
Create Date: 2026-08-17 13:59:55.228344
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


ENUM_TYPE_NAMES = ("approvalstatus", "memorykind", "workspacestatus")

revision: str = "9aeb8666b39c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approvals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("details_json", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "denied", "expired", name="approvalstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_approvals_conversation_id"),
        "approvals",
        ["conversation_id"],
        unique=False,
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("memory_enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "memory_entries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("profile", "episodic", "semantic", "preference", name="memorykind"),
            nullable=False,
        ),
        sa.Column("key", sa.String(length=128), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_memory_entries_conversation_id"),
        "memory_entries",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memory_entries_key"), "memory_entries", ["key"], unique=False
    )
    op.create_index(
        op.f("ix_memory_entries_kind"), "memory_entries", ["kind"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_messages_conversation_id"),
        "messages",
        ["conversation_id"],
        unique=False,
    )
    op.create_table(
        "workspaces",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "none",
                "starting",
                "running",
                "stopping",
                "stopped",
                "error",
                "unavailable",
                name="workspacestatus",
            ),
            nullable=False,
        ),
        sa.Column("provider_ref", sa.String(length=256), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("idle_timeout_sec", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("conversation_id", name="uq_workspace_conversation"),
    )
    op.create_index(
        op.f("ix_workspaces_conversation_id"),
        "workspaces",
        ["conversation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workspaces_conversation_id"), table_name="workspaces")
    op.drop_table("workspaces")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_memory_entries_kind"), table_name="memory_entries")
    op.drop_index(op.f("ix_memory_entries_key"), table_name="memory_entries")
    op.drop_index(
        op.f("ix_memory_entries_conversation_id"), table_name="memory_entries"
    )
    op.drop_table("memory_entries")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_approvals_conversation_id"), table_name="approvals")
    op.drop_table("approvals")
    if op.get_bind().dialect.name == "postgresql":
        for type_name in ENUM_TYPE_NAMES:
            sa.Enum(name=type_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
